---
name: Emporia Vue WebSocket
version: 0.0.1
slug: emporia_ws
description: WebSocket bridge for Emporia Vue using go-emporia-vue
url: https://github.com/alex-savin/hassio-apps/emporia-ws
arch:
  - amd64
  - arm64
  - armv7
startup: services
boot: auto
init: false
schema: {}
options: {}
ports:
  "8080/tcp": null
environment:
  ADDON_PORT: "8080"
image: "ghcr.io/alex-savin/emporia-ws-addon-{arch}"
