---
name: RTL-SDR Automatic Meter Reading (AMR) Receiver
version: 1.0.0
slug: rtlamr_ws
url: https://github.com/alex-savin/hassio-addon-rtlamr-ws
description: RTL-SDR Automatic Meter Reading Bridge
arch:
  - amd64
  - aarch64
init: false
uart: true
udev: true
usb: true
hassio_api: true
panel_icon: mdi:gauge
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Websocket and health endpoints (host port configurable)
options:
  general:
    sleep_for: 60
    verbosity: info
    device_id: "0"
  custom_parameters: {}
  meters:
    - id: 22222222
      protocol: r900
      name: water
      format: "######.###"
      unit_of_measurement: "gal"
      device_class: water
      state_class: total_increasing
schema:
  general:
    sleep_for: "int?"
    verbosity: "list(debug|info|warning|critical|none)?"
    device_id: "str?"
    rtltcp_host: match(([\w\d\.]+):(\d+))?
  custom_parameters:
    rtltcp: "str?"
    rtlamr: "str?"
  meters:
    - id: int
      protocol: list(idm|netidm|r900|r900bcd|scm|scm+)
      name: "str"
      format: "str?"
      unit_of_measurement: "str?"
      icon: "str?"
      device_class: list(none|current|energy|gas|power|water)
      state_class: list(measurement|total|total_increasing)?
      expire_after: int?
      force_update: bool?
image: "ghcr.io/alex-savin/{arch}-addon-rtlamr-ws"
